updpkg: devtools-riscv64 1:1.4.0+patch1-1
- The devtools package needs to be updated to 1:1.4.0-3 before building
  this package.
- Patch fortran.conf for riscv64
- Disable sandbox in pacman because some vendor kernels and qemu-user
  does not support it, with errors like:

    error: restricting filesystem access failed because Landlock is not supported by the kernel!
    error: switching to sandbox user 'alpm' failed!