addpatch: electron33 33.0.0-1
Changes at riscv-forks/electron:

Update patchset for electron33(chromium 130):
https://github.com/riscv-forks/electron/commit/c7dff70ce824285cf97ac77bbd9cc9a46580efd0

Packaging changes compared to electron 32:

Use native rollup instead of wasm rollup, to workaround wasm errors
like:

RuntimeError: Command '/build/electron33/src/src/third_party/node/linux/node-linux-x64/bin/node /build/electron33/src/src/third_party/node/node_modules/@rollup/wasm-node/dist/bin/rollup /build/electron33/src/src/out/Release/gen/third_pa
rty/lit/v3_0/lit.js --format esm --dir /build/electron33/src/src/out/Release/gen/third_party/lit/v3_0/bundled --entryFileNames [name].rollup.js --sourcemap --sourcemapExcludeSources --config ../../third_party/lit/v3_0/rollup.config.mjs'
 failed

/build/electron33/src/src/out/Release/gen/third_party/lit/v3_0/lit.js → gen/third_party/lit/v3_0/bundled...
[!] RuntimeError: unreachable
    at null.<anonymous> (wasm://wasm/005abe4a:1:1224394)
    at null.<anonymous> (wasm://wasm/005abe4a:1:1353214)
    at null.<anonymous> (wasm://wasm/005abe4a:1:998801)
    at null.<anonymous> (wasm://wasm/005abe4a:1:95196)
    at null.<anonymous> (wasm://wasm/005abe4a:1:93978)
    at null.<anonymous> (wasm://wasm/005abe4a:1:1037939)
    at null.<anonymous> (wasm://wasm/005abe4a:1:93359)
    at null.<anonymous> (wasm://wasm/005abe4a:1:91561)
    at null.<anonymous> (wasm://wasm/005abe4a:1:93978)
    at null.<anonymous> (wasm://wasm/005abe4a:1:218801)

I am not familiar with wasm debugging. Not sure if it is a v8 bug.