addpatch: mac 11.03-1
- Fix undefined reference to RVV functions, to be upstreamed via email
- Disable LTO since mixing rv64gc and rv64gcv objects conflicts with it