updpatch: nodejs 25.8.1-1
- Refresh patch
- This PR depends on #5171
- nocheck is needed because:

	[16:33:50.263] ERROR: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
	RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instancemake[1]: *** [Makefile:392: test/addons/.docbuildstamp] Error 1
	make: *** [Makefile:352: test-only] Error 2